# 此配置文件为系统使用，请勿修改，否则可能无法正常使用
# 用户配置已移动至 Yz/config/QBot-Plugin.yaml

admin:
  priorityTips: |-
    优先级
  priority: 0
  regTips: |-
    指令正则
  reg: ([Qq]?[Bb]ot)
QBotSet:
  markdownTips: |-
    机器人Markdown模式
    1: md格式 | 2: json格式 | 默认为false
  markdown: 0
  arkloginTips: |-
    登录是否使用ark
  arklogin: true
  dayTips: |-
    最近几天活跃
  day: 5
  countTips: |-
    是否开启机器人统计
  count: false
